- id: '1598456074209'
  alias: Turn the lights on at 5:00
  description: ''
  trigger:
  - at: 05:00:00
    platform: time
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.home_mode
      state: 'on'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - scene: scene.tant_nedanvaning
  mode: single
- id: '1598456107080'
  alias: Turn the lights off at 6:00
  description: ''
  trigger:
  - at: 06:00:00
    platform: time
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: person.andreas_olsson
      state: '"away"'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - scene: scene.slackt_nedanvaning
  mode: single
- id: '1598595594520'
  alias: Turn on - Home mode
  description: ''
  trigger:
  - entity_id: person.andreas_olsson
    from: not_home
    platform: state
    to: home
  - entity_id: person.evelina_mattsson
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: input_boolean.home_mode
    state: 'off'
  action:
  - data: {}
    entity_id: input_boolean.home_mode
    service: input_boolean.turn_on
  mode: single
- id: '1598595730040'
  alias: Turn off - Home mode
  description: ''
  trigger:
  - entity_id: person.andreas_olsson
    from: home
    platform: state
    to: not_home
  - entity_id: person.evelina_mattsson
    from: home
    platform: state
    to: not_home
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.home_mode
      state: 'on'
    - condition: state
      entity_id: person.andreas_olsson
      state: not_home
    - condition: state
      entity_id: person.evelina_mattsson
      state: not_home
  action:
  - data: {}
    entity_id: input_boolean.home_mode
    service: input_boolean.turn_off
  mode: single
- id: '1607177439120'
  alias: Turn on smart plugs when it's dark
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:45:00
  condition: []
  action:
  - scene: scene.smartplugs_pa
  mode: single
- id: '1607177580417'
  alias: Turn off smart plugs - Home mode On
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
  - condition: state
    entity_id: input_boolean.home_mode
    state: 'on'
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - scene: scene.smartplugs_av
  mode: single
- id: '1607177633176'
  alias: Turn off smart plugs - Home mode Off
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - scene: scene.smartplugs_av
  mode: single
- id: '1611125861930'
  alias: Send notification on Synology update available
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: b4dcc192f78b7ee5dc6d0cfbb9ac50a7
    entity_id: binary_sensor.ds415_update_available
    domain: binary_sensor
  condition: []
  action:
  - service: notify.mobile_app_figges_iphone
    data:
      title: Synology
      message: Update available
  mode: single
- id: '1611137295375'
  alias: Water detected upstairs
  description: ''
  trigger:
  - type: moist
    platform: device
    device_id: e1c187eaa5d847216eff7ce235cf4926
    entity_id: binary_sensor.upstairs_water
    domain: binary_sensor
  condition: []
  action:
  - service: notify.notify
    data:
      title: Water detected upstairs
      message: Possible leak
  mode: single
- id: '1611144694074'
  alias: Water detected downstairs
  description: ''
  trigger:
  - type: moist
    platform: device
    device_id: 98f19f6c4da6deb6f18943823482cd6f
    entity_id: binary_sensor.downstairs_water
    domain: binary_sensor
  condition: []
  action:
  - service: notify.notify
    data:
      title: Water detected downstairs
      message: Possible leak
  mode: single
