- platform: history_stats
  name: Quarantine meter Andreas
  entity_id: person.andreas_olsson
  state: "home"
  type: ratio
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: Quarantine meter Evelina
  entity_id: person.evelina_mattsson
  state: "home"
  type: ratio
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: Quarantine meter Andreas times left
  entity_id: person.andreas_olsson
  state: "home"
  type: count
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: Quarantine meter Evelina times left
  entity_id: person.evelina_mattsson
  state: "home"
  type: count
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: Livingroom TV turned on last 7 days
  entity_id: media_player.samsung_tv
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Bedroom TV turned on on last 7 days
  entity_id: media_player.sovrum
  state: "playing"
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Plex Streaming Hours last 7 days
  entity_id: sensor.plex_proxmox_plex
  state:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  duration:
    days: 7
  end: "{{ now() }}"
