- platform: history_stats
  name: Quarantine meter Andreas
  entity_id: person.andreas_olsson
  state: "home"
  type: ratio
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: Quarantine meter Evelina
  entity_id: person.evelina_mattsson
  state: "home"
  type: ratio
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: Quarantine meter Andreas times left
  entity_id: person.andreas_olsson
  state: "home"
  type: count
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: Quarantine meter Evelina times left
  entity_id: person.evelina_mattsson
  state: "home"
  type: count
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: Livingroom TV turned on last 7 days
  entity_id: media_player.samsung_tv
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Bedroom TV turned on on last 7 days
  entity_id: media_player.sovrum
  state: "playing"
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Plex Streaming Hours last 7 days
  entity_id: sensor.plex_proxmox_plex
  state:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  duration:
    days: 7
  end: "{{ now() }}"

- platform: nordpool
  # Should the prices include vat? Default True
  VAT: false
  # What currency the api fetches the prices in
  # this is only need if you want a sensor in a non local currency
  currency: "SEK"
  # Option to show prices in cents (or the equivalent in local currency)
  price_in_cents: false
  # Helper so you can set your "low" price
  # low_price = hour_price < average * low_price_cutoff
  low_price_cutoff: 0.95
  # What power regions your are interested in.
  # Possible values: "DK1", "DK2", "FI", "LT", "LV", "Oslo", "Kr.sand", "Bergen", "Molde", "Tr.heim", "Tromsø", "SE1", "SE2", "SE3","SE4", "SYS", "EE"
  region: "SE4"
  # How many decimals to use in the display of the price
  precision: 3
  # What the price should be displayed in default
  # Possible values: MWh, kWh and Wh
  # default: kWh
  price_type: kWh
  # This option allows the usage of a template to add a tariff.
  # now() always refers start of the hour of that price.
  # this way we can calculate the correct costs add that to graphs etc.
  # The price result of the additional_costs template expects this additional cost to be in kWh and not cents as a float
  # default {{0.0|float}}
  additional_costs: "{{0.0|float}}"
