background: var(--background-image)
title: Bunkeflovägen
views:
  - panel: false
    title: Home
    badges:
      - entity: person.andreas_olsson
      - entity: person.evelina_mattsson
      - entity: sensor.asuswrt_devices_connected
      - entity: sensor.asuswrt_download_speed
      - entity: sensor.asuswrt_upload_speed
      - entity: sun.sun
    cards:
      - type: weather-forecast
        entity: weather.bunkeflovagen_47
      - type: entities
        entities:
          - entity: input_boolean.home_mode
          - entity: input_boolean.guest_mode
          - entity: input_boolean.vacation_mode
        state_color: true
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.quarantine_meter_andreas
            color: green
            show_state: false
          - entity: sensor.quarantine_meter_evelina
            color: orange
            show_state: false
        name: Quarantine Meter
        hours_to_show: 168
        show:
          name: true
          legend: true
          icon: false
          labels: true
      - type: grid
        columns: 2
        cards:
          - type: gauge
            entity: sensor.quarantine_meter_evelina
            min: 0
            max: 100
            severity:
              green: 95
              yellow: 80
              red: 0
            name: Evelina home
          - type: gauge
            entity: sensor.quarantine_meter_andreas
            min: 0
            max: 100
            severity:
              green: 95
              yellow: 80
              red: 0
            name: Andreas home
      - type: grid
        columns: 2
        cards:
          - type: "custom:mini-graph-card"
            show:
              extrema: true
            entities:
              - entity: sensor.temperature_25
            name: "Livingroom Temperature"
            decimals: 1
            points_per_hour: 2
            hour24: true
            font_size_header: 12
            font_size: 90
          - type: "custom:mini-graph-card"
            show:
              extrema: true
            entities:
              - entity: sensor.bedroom_temperature
            name: "Bedroom Temperature"
            decimals: 1
            points_per_hour: 2
            hour24: true
            font_size_header: 12
            font_size: 90
          - type: "custom:mini-graph-card"
            show:
              extrema: true
            entities:
              - entity: sensor.andreas_temperature
            name: "Andreas Room Temperature"
            decimals: 1
            points_per_hour: 2
            hour24: true
            font_size_header: 12
            font_size: 90
          - type: "custom:mini-graph-card"
            show:
              extrema: true
            entities:
              - entity: sensor.nursery_temperature
            name: "Nursery Temperature"
            decimals: 1
            points_per_hour: 2
            hour24: true
            font_size_header: 12
            font_size: 90
          - type: "custom:mini-graph-card"
            show:
              extrema: true
            entities:
              - entity: sensor.patio_temperature_2
            name: "Patio Temperature"
            decimals: 1
            points_per_hour: 2
            hour24: true
            font_size_header: 12
            font_size: 90
  - panel: false
    title: Controls
    icon: mdi:remote
    cards:
      - type: entities
        title: Control Panel
        entities:
          - type: "custom:slider-entity-row"
            entity: light.hall
            toggle: true
          - type: "custom:slider-entity-row"
            entity: light.ytterdorr
            toggle: true
          - type: "custom:slider-entity-row"
            entity: light.matbord
            toggle: true
          - type: "custom:slider-entity-row"
            entity: light.sovrum_1
            toggle: true
          - type: "custom:slider-entity-row"
            entity: light.koksbord
            toggle: true
          - switch.smart_plug_kontor
          - switch.smart_plug_downstairs_livingroom
          - switch.smart_plug_runt_fonster
          - switch.smart_plug_upstairs_livingroom
          - switch.smart_plug_livias_rum
        state_color: true
        show_header_toggle: false
      - type: entities
        entities:
          - entity: scene.slackt_nedanvaning
            icon: "mdi:lightbulb-off-outline"
          - entity: scene.tant_nedanvaning
            icon: "mdi:lightbulb-outline"
          - entity: scene.mysbelysning_nedanvaning
            icon: "mdi:lightbulb-outline"
          - entity: scene.smartplugs_pa
            icon: "mdi:power-plug-outline"
          - entity: scene.smartplugs_av
            icon: "mdi:power-plug-off-outline"
          - entity: scene.tant_matbord
            icon: "mdi:table-furniture"
          - entity: scene.slackt_matbord
            icon: "mdi:table-furniture"
          - entity: scene.babyrum_tant
            icon: "mdi:baby"
          - entity: scene.babyrum_slackt
            icon: "mdi:baby"
          - entity: scene.tant_sovrum
            icon: "mdi:bed"
          - entity: scene.slackt_sovrum
            icon: "mdi:bed"
  - panel: false
    title: Details
    icon: mdi:chart-bar
    cards:
      - type: entities
        title: Electricity
        icon: mdi:flash
        show_header_toggle: false
        entities:
          - entity: sensor.nordpool_kwh_se4_sek_3_095_0
            name: Current price
            icon: mdi:cash-multiple
          - entity: sensor.nordpool_kwh_se4_sek_3_095_0
            type: attribute
            name: Min price
            suffix: SEK/kWh
            attribute: min
            icon: mdi:cash-multiple
          - entity: sensor.nordpool_kwh_se4_sek_3_095_0
            type: attribute
            name: Max price
            suffix: SEK/kWh
            attribute: max
            icon: mdi:cash-multiple
          - entity: sensor.nordpool_kwh_se4_sek_3_095_0
            type: attribute
            name: Average price
            suffix: SEK/kWh
            attribute: average
            icon: mdi:cash-multiple
      - type: entities
        title: Pi-hole
        entities:
          - entity: sensor.pi_hole_dns_queries_today
            name: Queries
          - entity: sensor.pi_hole_ads_blocked_today
            name: Ads blocked
          - entity: sensor.pi_hole_ads_percentage_blocked_today
            name: "% Blocked today"
      - type: "custom:mini-graph-card"
        show:
          extrema: true
          average: true
        entities:
          - entity: sensor.speedtest_download
        name: "Download"
        decimals: 1
        points_per_hour: 2
        hour24: true
        font_size_header: 12
        font_size: 90
      - type: "custom:mini-graph-card"
        show:
          extrema: true
          average: true
        entities:
          - entity: sensor.speedtest_upload
        name: "Upload"
        decimals: 1
        points_per_hour: 2
        hour24: true
        font_size_header: 12
        font_size: 90
      - type: entities
        title: DS415
        entities:
          - entity: binary_sensor.ds415_security_status
            name: Security Status
          - entity: sensor.ds415_drive_1_status
            name: Drive 1 Status
          - entity: sensor.ds415_drive_1_temperature
            name: Drive 1 Temperature
          - entity: sensor.ds415_drive_2_status
            name: Drive 2 Status
          - entity: sensor.ds415_drive_2_temperature
            name: Drive 2 Temperature
          - entity: sensor.ds415_drive_3_status
            name: Drive 3 Status
          - entity: sensor.ds415_drive_3_temperature
            name: Drive 3 Temperature
          - entity: sensor.ds415_drive_4_status
            name: Drive 4 Status
          - entity: sensor.ds415_drive_4_temperature
            name: Drive 4 Temperature
          - entity: sensor.ds415_volume_1_volume_used
            name: Used capacity
          - entity: sensor.ds415_volume_1_used_space
            name: Used space
      - type: entities
        title: Sensor Details
        entities:
          - entity: sensor.humidity_26
            name: Livingroom Humidity
          - entity: sensor.pressure_27
            name: Livingroom Pressure
          - entity: sensor.temperature_25_battery_level
            name: Livingroom Battery
          - entity: sensor.patio_humidity_2
            name: Patio Humidity
          - entity: sensor.patio_pressure_2
            name: Patio Pressure
          - entity: sensor.patio_sensor_battery_level
            name: Patio Battery
          - entity: sensor.andreas_humidity
            name: Andreas room Humidity
          - entity: sensor.andreas_pressure
            name: Andreas room Pressure
          - entity: sensor.andreas_sensor_battery_level
            name: Andreas room Battery
          - entity: sensor.bedroom_humidity
            name: Bedroom Humidity
          - entity: sensor.bedroom_pressure
            name: Bedroom Pressure
          - entity: sensor.bedroom_sensor_battery_level
            name: Bedroom Battery
          - entity: sensor.nursery_humidity
            name: Nursery Humidity
          - entity: sensor.nursery_pressure
            name: Nursery Pressure
          - entity: sensor.nursery_sensor_battery_level
            name: Nursery Battery
          - entity: binary_sensor.downstairs_water
          - entity: sensor.downstairs_water_battery_level
            name: Downstairs Watersensor Battery
          - entity: binary_sensor.upstairs_water
          - entity: sensor.upstairs_water_battery_level
            name: Upstairs Watersensor Battery
      - type: entities
        title: Plex
        entities:
          - entity: sensor.plex_proxmox_plex
            name: Status
          - entity: sensor.proxmox_plex_library_movies
            name: Movies
          - entity: sensor.proxmox_plex_library_tv_shows
            name: TV Shows
          - entity: sensor.proxmox_plex_library_klipp
            name: Clips
