background: var(--background-image)
title: Bunkeflovägen
views:
  - panel: false
    title: Home
    badges:
      - entity: person.andreas_olsson
      - entity: person.evelina_mattsson
      - entity: sensor.asuswrt_devices_connected
      - entity: sensor.asuswrt_download_speed
      - entity: sensor.asuswrt_upload_speed
      - entity: sun.sun
    cards:
      - type: weather-forecast
        entity: weather.bunkeflovagen_47
      - type: entities
        entities:
          - entity: input_boolean.home_mode
          - entity: input_boolean.guest_mode
          - entity: input_boolean.vacation_mode
        state_color: true
      - type: entities
        entities:
          - entity: alarm_control_panel.sector_alarmpanel_02147689
            name: Alarm status
          - entity: sensor.sector_overvaning_244014a747f
            name: Upstairs
          - entity: sensor.sector_undervaning_245014b6124
            name: Downstairs
        state_color: true
      - type: grid
        columns: 2
        cards:
          - type: gauge
            entity: sensor.quarantine_meter_evelina
            min: 0
            max: 100
            severity:
              green: 95
              yellow: 80
              red: 0
            name: Evelina home
          - type: gauge
            entity: sensor.quarantine_meter_andreas
            min: 0
            max: 100
            severity:
              green: 95
              yellow: 80
              red: 0
            name: Andreas home
      - type: grid
        columns: 3
        cards:
          - type: entity
            entity: sensor.bedroom_tv_turned_on_on_last_7_days
            name: Bedroom
            icon: "mdi:bed-king-outline"
          - type: entity
            entity: sensor.livingroom_tv_turned_on_last_7_days
            name: Livingroom
            icon: "mdi:television"
          - type: entity
            entity: sensor.plex_streaming_hours_last_7_days
            name: Plex
            icon: "mdi:plex"
      - type: grid
        columns: 2
        cards:
          - type: sensor
            entity: sensor.temperature_25
            graph: line
            hours_to_show: 24
            detail: 1
            icon: "mdi:thermometer"
          - type: sensor
            entity: sensor.bedroom_temperature
            graph: line
            hours_to_show: 24
            detail: 1
            icon: "mdi:thermometer"
          - type: sensor
            entity: sensor.andreas_temperature
            graph: line
            hours_to_show: 24
            detail: 1
            icon: "mdi:thermometer"
          - type: sensor
            entity: sensor.patio_temperature_2
            graph: line
            hours_to_show: 24
            detail: 1
            icon: "mdi:thermometer"
          - type: sensor
            entity: sensor.nursery_temperature
            graph: line
            hours_to_show: 24
            detail: 1
            icon: "mdi:thermometer"
  - panel: false
    title: Controls
    icon: mdi:remote
    cards:
      - type: glance
        title: Control Panel
        entities:
          - entity: light.hall_1
          - entity: light.hall_2
          - entity: light.hall_3
          - entity: light.ytterdorr_1
          - entity: light.ytterdorr_2
          - entity: light.ytterdorr_3
          - entity: light.sovrum_1
          - entity: light.koksbord
          - entity: light.matbord_1
          - entity: light.matbord_2
          - entity: light.matbord_3
          - entity: light.matbord_4
          - entity: switch.andreas_rum
          - entity: switch.bebisrum
          - entity: switch.smart_plug_downstairs_livingroom
          - entity: switch.runt_fonster
          - entity: switch.smart_plug_upstairs_livingroom
        state_color: true
      - type: entities
        entities:
          - entity: scene.slackt_nedanvaning
            icon: "mdi:lightbulb-off-outline"
          - entity: scene.tant_nedanvaning
            icon: "mdi:lightbulb-outline"
          - entity: scene.mysbelysning_nedanvaning
            icon: "mdi:lightbulb-outline"
          - entity: scene.smartplugs_pa
            icon: "mdi:power-plug-outline"
          - entity: scene.smartplugs_av
            icon: "mdi:power-plug-off-outline"
          - entity: scene.tant_matbord
            icon: "mdi:table-furniture"
          - entity: scene.slackt_matbord
            icon: "mdi:table-furniture"
          - entity: scene.babyrum_tant
            icon: "mdi:baby"
          - entity: scene.babyrum_slackt
            icon: "mdi:baby"
          - entity: scene.tant_sovrum
            icon: "mdi:bed"
          - entity: scene.slackt_sovrum
            icon: "mdi:bed"
  - panel: false
    title: Details
    icon: mdi:chart-bar
    cards:
      - type: entities
        title: Pi-hole
        entities:
          - entity: sensor.pi_hole_dns_queries_today
            name: Queries
          - entity: sensor.pi_hole_ads_blocked_today
            name: Ads blocked
          - entity: sensor.pi_hole_ads_percentage_blocked_today
            name: "% Blocked today"
      - type: entities
        title: DS415
        entities:
          - entity: binary_sensor.ds415_update_available
            name: Update Available
          - entity: binary_sensor.ds415_security_status
            name: Security Status
          - entity: sensor.ds415_drive_1_status
            name: Drive 1 Status
          - entity: sensor.ds415_drive_1_temperature
            name: Drive 1 Temperature
          - entity: sensor.ds415_drive_2_status
            name: Drive 2 Status
          - entity: sensor.ds415_drive_2_temperature
            name: Drive 2 Temperature
          - entity: sensor.ds415_drive_3_status
            name: Drive 3 Status
          - entity: sensor.ds415_drive_3_temperature
            name: Drive 3 Temperature
          - entity: sensor.ds415_drive_4_status
            name: Drive 4 Status
          - entity: sensor.ds415_drive_4_temperature
            name: Drive 4 Temperature
          - entity: sensor.ds415_volume_1_volume_used
            name: Used capacity
      - type: entities
        title: Sensor Details
        entities:
          - entity: sensor.humidity_26
            name: Livingroom Humidity
          - entity: sensor.pressure_27
            name: Livingroom Pressure
          - entity: sensor.temperature_25_battery_level
            name: Livingroom Battery
          - entity: sensor.patio_humidity_2
            name: Patio Humidity
          - entity: sensor.patio_pressure_2
            name: Patio Pressure
          - entity: sensor.patio_sensor_battery_level
            name: Patio Battery
          - entity: sensor.andreas_humidity
            name: Andreas room Humidity
          - entity: sensor.andreas_pressure
            name: Andreas room Pressure
          - entity: sensor.andreas_sensor_battery_level
            name: Andreas room Battery
          - entity: sensor.bedroom_humidity
            name: Bedroom Humidity
          - entity: sensor.bedroom_pressure
            name: Bedroom Pressure
          - entity: sensor.bedroom_sensor_battery_level
            name: Bedroom Battery
          - entity: sensor.nursery_humidity
            name: Nursery Humidity
          - entity: sensor.nursery_pressure
            name: Nursery Pressure
          - entity: sensor.nursery_sensor_battery_level
            name: Nursery Battery
          - entity: binary_sensor.downstairs_water
          - entity: sensor.downstairs_water_battery_level
            name: Downstairs Watersensor Battery
          - entity: binary_sensor.upstairs_water
          - entity: sensor.upstairs_water_battery_level
            name: Upstairs Watersensor Battery
