title: Bunkeflovägen
views:
  - panel: false
    title: Bunkeflovägen 47
    badges:
      - entity: person.andreas_olsson
      - entity: person.evelina_mattsson
      - entity: sensor.asuswrt_devices_connected
      - entity: sensor.asuswrt_download_speed
      - entity: sensor.asuswrt_upload_speed
      - entity: sun.sun
    cards:
      - type: weather-forecast
        entity: weather.bunkeflovagen_47
      - type: entities
        entities:
          - entity: input_boolean.home_mode
          - entity: input_boolean.guest_mode
          - entity: input_boolean.vacation_mode
        state_color: true
      # - type: vertical-stack
      #   cards:
      #     - type: history-graph
      #       entities:
      #         - entity: sensor.transmission_up_speed
      #         - entity: sensor.transmission_down_speed
      #       hours_to_show: 24
      #       refresh_interval: 0
      #       #title: Transmission
      - type: entities
        entities:
          - entity: scene.slackt_nedanvaning
            icon: "mdi:lightbulb-off-outline"
          - entity: scene.tant_nedanvaning
            icon: "mdi:lightbulb-outline"
          - entity: scene.mysbelysning_nedanvaning
            icon: "mdi:lightbulb-outline"
          - entity: scene.smartplugs_pa
            icon: "mdi:power-plug-outline"
          - entity: scene.smartplugs_av
            icon: "mdi:power-plug-off-outline"
          - entity: scene.tant_matbord
            icon: "mdi:table-furniture"
          - entity: scene.slackt_matbord
            icon: "mdi:table-furniture"
      - content: >-
          ## Quarantine-o-meter

          The gauge meters display the amount of time spend at home in the last
          7 days. Where Andreas left the house (on average) {{
          (states("sensor.quarantine_meter_andreas_times_left")|int / 7) |
          round(1) }} times per day and Evelina {{
          (states("sensor.quarantine_meter_evelina_times_left")|int / 7) |
          round(1) }} times per day.
        type: markdown
      - type: grid
        columns: 2
        cards:
          - type: gauge
            entity: sensor.quarantine_meter_evelina
            min: 0
            max: 100
            severity:
              green: 95
              yellow: 80
              red: 0
            name: Evelina
          - type: gauge
            entity: sensor.quarantine_meter_andreas
            min: 0
            max: 100
            severity:
              green: 95
              yellow: 80
              red: 0
            name: Andreas
      - type: glance
        title: Control Panel
        entities:
          - entity: light.hall_1
          - entity: light.hall_2
          - entity: light.hall_3
          - entity: light.ytterdorr_1
          - entity: light.ytterdorr_2
          - entity: light.ytterdorr_3
          - entity: light.sovrum_1
          - entity: light.koksbord
          - entity: light.matbord_1
          - entity: light.matbord_2
          - entity: light.matbord_3
          - entity: light.matbord_4
          - entity: switch.andreas_rum
          - entity: switch.bebisrum
          - entity: switch.bredvid_tv
          - entity: switch.runt_fonster
          - entity: switch.vardagsrum_uppe
        state_color: true
      - type: grid
        title: Temperatures
        columns: 2
        cards:
          - type: sensor
            entity: sensor.temperature_25
            graph: line
            hours_to_show: 12
            detail: 2
            icon: "mdi:thermometer"
          - type: sensor
            entity: sensor.bedroom_temperature
            graph: line
            hours_to_show: 12
            detail: 2
            icon: "mdi:thermometer"
          - type: sensor
            entity: sensor.andreas_temperature
            graph: line
            hours_to_show: 12
            detail: 2
            icon: "mdi:thermometer"
          - type: sensor
            entity: sensor.patio_temperature_2
            graph: line
            hours_to_show: 12
            detail: 2
            icon: "mdi:thermometer"
      - type: grid
        title: 7 Day Stats
        columns: 3
        cards:
          - type: entity
            entity: sensor.bedroom_tv_turned_on_on_last_7_days
            name: Bedroom
            icon: "mdi:bed-king-outline"
          - type: entity
            entity: sensor.livingroom_tv_turned_on_last_7_days
            name: Livingroom
            icon: "mdi:television"
          - type: entity
            entity: sensor.plex_streaming_hours_last_7_days
            name: Plex
            icon: "mdi:plex"
      # - type: grid
      #   columns: 2
      #   cards:
      #     - type: sensor
      #       entity: sensor.transmission_down_speed
      #       name: Download Speed
      #       graph: line
      #       hours_to_show: 24
      #       detail: 1
      #       icon: "mdi:download-network-outline"
      #     - type: sensor
      #       entity: sensor.transmission_up_speed
      #       name: Upload Speed
      #       graph: line
      #       hours_to_show: 24
      #       detail: 1
      #       icon: "mdi:upload-network-outline"
      #     - type: gauge
      #       entity: sensor.ds415_volume_1_volume_used
      #       min: 0
      #       max: 100
      #       severity:
      #         green: 95
      #         yellow: 80
      #         red: 0
      #       name: Used capacity (DS415)
      - type: entities
        title: Details
        entities:
          - entity: sensor.humidity_26
            name: Livingroom Humidity
          - entity: sensor.pressure_27
            name: Livingroom Pressure
          - entity: sensor.temperature_25_battery_level
            name: Livingroom Battery
          - entity: sensor.patio_humidity_2
            name: Patio Humidity
          - entity: sensor.patio_pressure_2
            name: Patio Pressure
          - entity: sensor.patio_sensor_battery_level
            name: Patio Battery
          - entity: sensor.andreas_humidity
            name: Andreas room Humidity
          - entity: sensor.andreas_pressure
            name: Andreas room Pressure
          - entity: sensor.andreas_sensor_battery_level
            name: Andreas room Battery
          - entity: sensor.bedroom_humidity
            name: Bedroom Humidity
          - entity: sensor.bedroom_pressure
            name: Bedroom Pressure
          - entity: sensor.bedroom_sensor_battery_level
            name: Bedroom Battery
          - entity: binary_sensor.downstairs_water
          - entity: sensor.downstairs_water_battery_level
            name: Downstairs Watersensor Battery
          - entity: binary_sensor.upstairs_water
          - entity: sensor.upstairs_water_battery_level
            name: Upstairs Watersensor Battery
